version: '3.9'

services:
  jakarta-app:
    image: evertonagilar/jakartaapp:1.0.0
    build:
      context: .
    environment:
      - PAYARA_ARGS=--debug
      - TOKEN=123456
    ports:
      - "8080:8080"
      - "4848:4848"
      - "9009:9009"

